# Generated by Django 3.1.3 on 2020-11-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttncode', models.CharField(max_length=20, unique=True)),
                ('testResult', models.CharField(max_length=60)),
                ('fullname', models.CharField(max_length=30)),
                ('emailid', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
            ],
        ),
    ]
