# Generated by Django 3.1.3 on 2020-11-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCoVTestHubApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virustesting',
            name='ttn',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
