# Generated by Django 3.1.3 on 2020-11-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCoVTestHubApplication', '0002_auto_20201119_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virustesting',
            name='ttn',
            field=models.CharField(error_messages={'unique': 'This TTN has already been used.'}, max_length=100, unique=True),
        ),
    ]
