# Generated by Django 3.1.3 on 2020-11-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCoVTestHubApplication', '0004_auto_20201121_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virustesting',
            name='email',
            field=models.CharField(error_messages={'unique': 'This EMAIL has already been used.'}, max_length=100, unique=True),
        ),
    ]
