# Generated by Django 3.1.3 on 2020-11-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCoVTestHubApplication', '0006_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivenTTN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenTTN', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
