# Generated by Django 3.1.3 on 2020-11-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirusTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ttn', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=1)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
