# Generated by Django 3.1.3 on 2020-11-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCoVTestHubApplication', '0007_giventtn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GivenTTN',
        ),
    ]
