# Generated by Django 3.1.3 on 2020-11-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCoVTestHubApplication', '0009_giventtn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giventtn',
            name='givenTTN',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
