# Generated by Django 3.1.3 on 2020-11-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virusTestingApp', '0003_auto_20201125_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='font_size',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
