# Generated by Django 3.1.3 on 2020-11-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('gender', models.TextField(max_length=2000)),
                ('address', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('ttn', models.CharField(max_length=200)),
                ('testResult', models.TextField(max_length=1000)),
            ],
        ),
    ]
