# Generated by Django 3.1.3 on 2020-11-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virusTestingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='RegisteredUser',
        ),
    ]
